#!/usr/bin/bash
THIS_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
DIR_WD="${THIS_DIR}/.."
DIR_PACKAGE="yolov5"

pushd ${DIR_WD}
mkdir -p ${DIR_PACKAGE}
ln -srTf models ${DIR_PACKAGE}/models
ln -srTf utils ${DIR_PACKAGE}/utils
touch ${DIR_PACKAGE}/__init__.py
popd
